package com.fairdeal;

import net.milkbowl.vault.economy.Economy;
import io.papermc.paper.math.Position;
import org.bukkit.block.sign.Side;
import net.milkbowl.vault.economy.EconomyResponse;
import org.bukkit.*;
import org.bukkit.command.*;
import org.bukkit.entity.Player;
import org.bukkit.event.*;
import org.bukkit.event.inventory.*;
import org.bukkit.event.block.SignChangeEvent;
import org.bukkit.event.player.*;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.plugin.RegisteredServiceProvider;
import org.bukkit.plugin.java.JavaPlugin;
import com.fairdeal.placeholder.FairDealExpansion;
import com.fairdeal.api.FairDealTradeEvent;
import com.fairdeal.util.MoneyAmountParser;
import java.io.File;
import java.sql.*;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/** FairDeal's secure two-party state machine. All Bukkit inventory access occurs in event handlers. */
public final class FairDealPlugin extends JavaPlugin implements Listener, CommandExecutor, TabCompleter {
  private final Map<UUID, Request> requests = new ConcurrentHashMap<>();
  private final Map<UUID, Trade> trades = new ConcurrentHashMap<>();
  private final Set<UUID> optOut = ConcurrentHashMap.newKeySet();
  private final Set<UUID> moneyInput = ConcurrentHashMap.newKeySet();
  private final Map<UUID, Location> signInputs = new ConcurrentHashMap<>();
  /** Guards the close event raised while the plugin redraws a trade screen. */
  private final Set<UUID> redrawing = ConcurrentHashMap.newKeySet();
  private Economy economy; private Connection database; private org.bukkit.configuration.file.YamlConfiguration messages;

  @Override public void onEnable() {
    saveDefaultConfig(); validateConfiguration(); saveResource("messages.yml", false); messages=org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(new File(getDataFolder(),"messages.yml"));
    getCommand("trade").setExecutor(this); getCommand("trade").setTabCompleter(this);
    getCommand("fairdealadmin").setExecutor(this); getCommand("fairdealadmin").setTabCompleter(this);
    getServer().getPluginManager().registerEvents(this, this);
    setupEconomy(); openDatabase(); pruneLogs(); recoverEscrows(); recoverCrashFiles(); recoverTransactions(); getServer().getGlobalRegionScheduler().runAtFixedRate(this, task -> expireRequests(), 20L, 20L); if (getServer().getPluginManager().getPlugin("PlaceholderAPI") != null) new FairDealExpansion(this).register();
  }
  @Override public void onDisable() { for (Trade t : new HashSet<>(trades.values())) cancel(t, "Server shutdown"); closeDatabase(); }
  private void updateTransaction(Trade t,String state,String reason){if(database==null)return;try(PreparedStatement s=database.prepareStatement("INSERT INTO transactions(id,first_uuid,second_uuid,state,updated_at,reason) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET state=excluded.state,updated_at=excluded.updated_at,reason=excluded.reason")){s.setString(1,t.id.toString());s.setString(2,t.a.toString());s.setString(3,t.b.toString());s.setString(4,state);s.setString(5,Instant.now().toString());s.setString(6,reason);s.executeUpdate();}catch(SQLException e){getLogger().severe("Could not update transaction journal: "+e.getMessage());}}
  private void validateConfiguration(){for(String material:getConfig().getStringList("blacklist"))try{Material.valueOf(material.toUpperCase(Locale.ROOT));}catch(IllegalArgumentException e){getLogger().warning("Unknown blacklist material in config: "+material);}for(String key:getConfig().getStringList("blacklist-custom-keys"))if(NamespacedKey.fromString(key)==null)getLogger().warning("Invalid custom blacklist key in config: "+key);for(String path:List.of("ui.lock-material","ui.confirmed-material"))uiMaterial(path,Material.STONE);}
    private void setupEconomy() { RegisteredServiceProvider<Economy> p=getServer().getServicesManager().getRegistration(Economy.class); if(p!=null)economy=p.getProvider(); }
  private void openDatabase() { try { getDataFolder().mkdirs(); database=DriverManager.getConnection("jdbc:sqlite:"+new File(getDataFolder(),"fairdeal.db").getAbsolutePath()); try(Statement s=database.createStatement()){s.executeUpdate("CREATE TABLE IF NOT EXISTS trade_log (id INTEGER PRIMARY KEY AUTOINCREMENT, time TEXT, first_uuid TEXT, second_uuid TEXT, status TEXT, first_money REAL, second_money REAL, reason TEXT, item_summary TEXT, first_name TEXT, second_name TEXT)"); try{s.executeUpdate("ALTER TABLE trade_log ADD COLUMN item_summary TEXT");}catch(SQLException ignored){} try{s.executeUpdate("ALTER TABLE trade_log ADD COLUMN first_name TEXT");}catch(SQLException ignored){} try{s.executeUpdate("ALTER TABLE trade_log ADD COLUMN second_name TEXT");}catch(SQLException ignored){} s.executeUpdate("CREATE TABLE IF NOT EXISTS transactions (id TEXT PRIMARY KEY, first_uuid TEXT, second_uuid TEXT, state TEXT NOT NULL, updated_at TEXT NOT NULL, reason TEXT)"); s.executeUpdate("CREATE TABLE IF NOT EXISTS escrow (owner_uuid TEXT PRIMARY KEY, amount REAL NOT NULL, updated_at TEXT NOT NULL)");} } catch(SQLException e){getLogger().severe("SQLite unavailable: "+e.getMessage());} }
  private void closeDatabase(){try{if(database!=null)database.close();}catch(SQLException ignored){}}
  /** Deletes only completed/cancelled history older than the configured retention period. */
  private void pruneLogs(){int days=getConfig().getInt("logs.retention-days",0);if(days<=0)return;File auditDir=new File(getDataFolder(),"audit");File[] audits=auditDir.listFiles((dir,name)->name.endsWith(".yml"));if(audits!=null){long cutoff=System.currentTimeMillis()-days*86400000L;for(File audit:audits)if(audit.lastModified()<cutoff&&!audit.delete())getLogger().warning("Could not prune audit "+audit.getName());}if(database==null)return;try(PreparedStatement s=database.prepareStatement("DELETE FROM trade_log WHERE time < ?")){s.setString(1,Instant.now().minusSeconds(days*86400L).toString());s.executeUpdate();}catch(SQLException e){getLogger().warning("Could not prune old trade logs: "+e.getMessage());}}
  /** Marks unfinished crash-era transactions as recovered after escrow and custody replay. */
  private void recoverTransactions(){if(database==null)return;try(PreparedStatement s=database.prepareStatement("UPDATE transactions SET state='REFUNDED', updated_at=?, reason='Recovered after server restart' WHERE state IN ('PREPARED','ESCROWED','COMPLETING')")){s.setString(1,Instant.now().toString());s.executeUpdate();}catch(SQLException e){getLogger().severe("Could not finalize recovered transactions: "+e.getMessage());}}
  /** Refunds journaled escrow left by an unclean server stop before players can trade again. */
  private void recoverEscrows(){if(database==null||economy==null)return;try(PreparedStatement s=database.prepareStatement("SELECT owner_uuid,amount FROM escrow");ResultSet r=s.executeQuery()){while(r.next()){UUID owner=UUID.fromString(r.getString("owner_uuid"));double amount=r.getDouble("amount");EconomyResponse result=economy.depositPlayer(getServer().getOfflinePlayer(owner),amount);if(result.transactionSuccess())clearEscrow(owner);else getLogger().severe("Could not refund recovered escrow for "+owner+": "+result.errorMessage);}}catch(Exception e){getLogger().severe("Could not recover money escrow: "+e.getMessage());}}
  private String describeOffer(ItemStack[] items){StringBuilder out=new StringBuilder();for(ItemStack item:items)if(item!=null&&item.getType()!=Material.AIR){if(!out.isEmpty())out.append(", ");out.append(item.getAmount()).append("x ").append(item.getType().name());}return out.isEmpty()?"No items":out.toString();}
  private void saveAudit(Trade t,String status,String reason){try{File dir=new File(getDataFolder(),"audit");dir.mkdirs();org.bukkit.configuration.file.YamlConfiguration y=new org.bukkit.configuration.file.YamlConfiguration();y.set("time",Instant.now().toString());y.set("status",status);y.set("reason",reason);y.set("first.uuid",t.a.toString());y.set("second.uuid",t.b.toString());y.set("first.money",t.moneyA);y.set("second.money",t.moneyB);y.set("first.items",Arrays.asList(t.offerA));y.set("second.items",Arrays.asList(t.offerB));y.save(new File(dir,Instant.now().toEpochMilli()+"-"+t.a+"-"+t.b+".yml"));}catch(Exception e){getLogger().warning("Could not save full trade audit: "+e.getMessage());}}
  private void log(Trade t,String status,String reason){ saveAudit(t,status,reason); if(database==null)return; try(PreparedStatement s=database.prepareStatement("INSERT INTO trade_log(time,first_uuid,second_uuid,status,first_money,second_money,reason,item_summary,first_name,second_name) VALUES(?,?,?,?,?,?,?,?,?,?)")){s.setString(1, Instant.now().toString());s.setString(2,t.a.toString());s.setString(3,t.b.toString());s.setString(4,status);s.setDouble(5,t.moneyA);s.setDouble(6,t.moneyB);s.setString(7,reason);s.setString(8,describeOffer(t.offerA)+" || "+describeOffer(t.offerB));Player first=getServer().getPlayer(t.a),second=getServer().getPlayer(t.b);s.setString(9,first==null?t.a.toString():first.getName());s.setString(10,second==null?t.b.toString():second.getName());s.executeUpdate();}catch(SQLException e){getLogger().warning("Could not log trade: "+e.getMessage());}}
  private String msg(String key){return ChatColor.translateAlternateColorCodes('&',messages.getString(key,"&cMissing message"));}
  private void tell(Player p,String text){p.sendMessage(msg("prefix")+ChatColor.translateAlternateColorCodes('&',text));}
  private void sound(Player p,String key){if(!getConfig().getBoolean("sounds.enabled",true))return;try{p.playSound(p.getLocation(),Sound.valueOf(getConfig().getString("sounds."+key,"ENTITY_EXPERIENCE_ORB_PICKUP")),1f,1f);}catch(IllegalArgumentException ignored){}}
  private boolean fire(Player first, Player second, FairDealTradeEvent.Stage stage, String reason) {
    FairDealTradeEvent event = new FairDealTradeEvent(first, second, stage, reason);
    getServer().getPluginManager().callEvent(event);
    return !event.isCancelled();
  }
  private boolean active(UUID id){return trades.containsKey(id);}
  public boolean isTrading(UUID id){return active(id);}
  public int tradeCount(UUID owner, String status){if(database==null)return 0;try(PreparedStatement s=database.prepareStatement("SELECT COUNT(*) FROM trade_log WHERE status=? AND (first_uuid=? OR second_uuid=?)")){s.setString(1,status);s.setString(2,owner.toString());s.setString(3,owner.toString());ResultSet r=s.executeQuery();return r.next()?r.getInt(1):0;}catch(SQLException e){return 0;}}
  public double moneyStat(UUID owner, boolean sent){if(database==null)return 0;String expression=sent?"CASE WHEN first_uuid=? THEN first_money ELSE second_money END":"CASE WHEN first_uuid=? THEN second_money ELSE first_money END";try(PreparedStatement s=database.prepareStatement("SELECT COALESCE(SUM("+expression+"),0) FROM trade_log WHERE status='COMPLETED' AND (first_uuid=? OR second_uuid=?)")){s.setString(1,owner.toString());s.setString(2,owner.toString());s.setString(3,owner.toString());ResultSet r=s.executeQuery();return r.next()?r.getDouble(1):0;}catch(SQLException e){return 0;}}
  public int recoveryCount(UUID owner){File f=new File(getDataFolder(),"recovery-"+owner+".yml"); return org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(f).getList("items", List.of()).size();}
  @Override public boolean onCommand(CommandSender sender,Command cmd,String label,String[] args){
    if(!(sender instanceof Player p)){sender.sendMessage("Players only.");return true;}
    if(cmd.getName().equalsIgnoreCase("fairdealadmin")){ if(!p.hasPermission("fairdeal.admin")){p.sendMessage(ChatColor.RED+"No permission.");return true;} if(args.length>0&&args[0].equalsIgnoreCase("reload")){reloadConfig(); validateConfiguration(); messages=org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(new File(getDataFolder(),"messages.yml")); pruneLogs(); tell(p,"&aConfiguration reloaded. Active trades are unchanged.");}
      else if(args.length>0&&args[0].equalsIgnoreCase("logs")){ UUID subject=null; if(args.length>1) subject=getServer().getOfflinePlayer(args[1]).getUniqueId(); showLogs(p,subject); }
      else if(args.length>0&&args[0].equalsIgnoreCase("inbox")&&args.length>1){showRecoveryView(p,getServer().getOfflinePlayer(args[1]).getUniqueId());}
      else if(args.length>0&&args[0].equalsIgnoreCase("diagnostics")){tell(p,"&eFairDeal diagnostics:");tell(p,"&7Economy: &f"+(economy==null?"Unavailable":economy.getName()));tell(p,"&7Storage: &f"+(database==null?"Unavailable":"SQLite"));tell(p,"&7Active trades: &f"+new HashSet<>(trades.values()).size());tell(p,"&7Pending requests: &f"+requests.size());}
      else if(args.length>0&&args[0].equalsIgnoreCase("active")){showActive(p);}
      else tell(p,"&e/fairdealadmin reload|logs [player]|inbox <player>|active|diagnostics"); return true; }
    if(args.length==0){tell(p,"&e/trade <player>|accept|deny|cancel|inbox|log|toggle");return true;}
    String sub=args[0].toLowerCase(Locale.ROOT);
    if(sub.equals("inbox")&&!p.hasPermission("fairdeal.inbox")){tell(p,msg("permission-denied"));return true;}
    if(sub.equals("log")&&!p.hasPermission("fairdeal.log")){tell(p,msg("permission-denied"));return true;}
    if(sub.equals("toggle")&&!p.hasPermission("fairdeal.toggle")){tell(p,msg("permission-denied"));return true;}
    if(!sub.equals("inbox")&&!sub.equals("log")&&!sub.equals("toggle")&&!p.hasPermission("fairdeal.use")){tell(p,msg("permission-denied"));return true;}
    if(sub.equals("accept")){ Request r=requests.remove(p.getUniqueId()); if(r==null||r.expires<System.currentTimeMillis()){tell(p,msg("no-request"));return true;} Player from=getServer().getPlayer(r.from);if(from==null){tell(p,"&cThat player is offline.");return true;} start(from,p);return true; }
    if(sub.equals("deny")){Request r=requests.remove(p.getUniqueId());if(r!=null){Player f=getServer().getPlayer(r.from);if(f!=null)tell(f,"&cTrade request denied.");}return true;}
    if(sub.equals("cancel")){Trade t=trades.get(p.getUniqueId());if(t!=null)cancel(t,"Cancelled by player");else tell(p,"&cYou are not trading.");return true;}
    if(sub.equals("toggle")){if(optOut.contains(p.getUniqueId())){optOut.remove(p.getUniqueId());tell(p,"&aIncoming trades enabled.");}else{optOut.add(p.getUniqueId());tell(p,"&eIncoming trades disabled.");}return true;}
    if(sub.equals("inbox")){showInbox(p);return true;} if(sub.equals("log")){showLogs(p,p.getUniqueId());return true;}
    Player target=getServer().getPlayerExact(args[0]); if(target==null||target.equals(p)){tell(p,"&cThat player cannot be traded with.");return true;} if(active(p.getUniqueId())||active(target.getUniqueId())){tell(p,"&cOne of you is already trading.");return true;} if(optOut.contains(target.getUniqueId())){tell(p,"&cThat player is not accepting trade requests.");return true;}
    if(!fire(p,target,FairDealTradeEvent.Stage.REQUEST,"Trade request")) { tell(p,msg("trade-blocked")); return true; } requests.put(target.getUniqueId(),new Request(p.getUniqueId(),System.currentTimeMillis()+getConfig().getLong("request-timeout-seconds",30)*1000));tell(p,msg("request-sent").replace("{player}",target.getName()));tell(target,msg("request-received").replace("{player}",p.getName()));sound(p,"request");sound(target,"request");return true;
  }
  private void expireRequests(){long now=System.currentTimeMillis();requests.entrySet().removeIf(entry->{if(entry.getValue().expires>=now)return false;Player target=getServer().getPlayer(entry.getKey());Player sender=getServer().getPlayer(entry.getValue().from);if(target!=null)tell(target,msg("request-expired"));if(sender!=null)tell(sender,msg("request-expired"));return true;});}
    private void start(Player a,Player b){if(!fire(a,b,FairDealTradeEvent.Stage.ACCEPT,"Accepted")) { tell(a,"&cThat trade was blocked."); tell(b,"&cThat trade was blocked."); return; } Trade t=new Trade(a.getUniqueId(),b.getUniqueId());updateTransaction(t,"PREPARED","Accepted");trades.put(t.a,t);trades.put(t.b,t);open(t,a);open(t,b);}
  private void open(Trade t,Player viewer){ Player other=getServer().getPlayer(t.other(viewer.getUniqueId())); Inventory inv=Bukkit.createInventory(new TradeHolder(t,viewer.getUniqueId()),54,ChatColor.translateAlternateColorCodes('&',getConfig().getString("trade-title","&8FairDeal: &a{player}").replace("{player}",other==null?"Offline":other.getName()))); for(int i=0;i<54;i++)inv.setItem(i,glass()); for(int i=0;i<27;i++){ItemStack x=t.offer(viewer.getUniqueId())[i];if(x!=null)inv.setItem(i,x);ItemStack y=t.offer(t.other(viewer.getUniqueId()))[i];if(y!=null)inv.setItem(27+i,y);} inv.setItem(45,button(Material.GOLD_INGOT,"&6Money: "+format(t.money(viewer.getUniqueId())),"&7Click to set an escrow amount")); inv.setItem(47,button(uiMaterial(t.locked(viewer.getUniqueId())?"confirmed-material":"lock-material",t.locked(viewer.getUniqueId())?Material.LIME_DYE:Material.GRAY_DYE),t.locked(viewer.getUniqueId())?"&aLocked":"&eLock offer","&7Lock your offer after reviewing it")); inv.setItem(49,button(Material.BARRIER,"&cCancel","&7Return all offers")); inv.setItem(51,button(t.bothLocked()?Material.EMERALD:Material.REDSTONE,t.confirmed(viewer.getUniqueId())?"&aConfirmed":"&aConfirm trade","&7Available after both offers lock")); viewer.openInventory(inv); }
  private Material uiMaterial(String path,Material fallback){try{return Material.valueOf(getConfig().getString("ui."+path,fallback.name()).toUpperCase(Locale.ROOT));}catch(Exception ignored){return fallback;}}
  private ItemStack glass(){return button(Material.BLACK_STAINED_GLASS_PANE," ","");} private ItemStack button(Material m,String n,String lore){ItemStack i=new ItemStack(m);ItemMeta x=i.getItemMeta();x.setDisplayName(ChatColor.translateAlternateColorCodes('&',n));x.setLore(List.of(ChatColor.translateAlternateColorCodes('&',lore)));i.setItemMeta(x);return i;}
  private boolean isBlacklisted(ItemStack item){if(getConfig().getStringList("blacklist").contains(item.getType().name()))return true;ItemMeta meta=item.getItemMeta();if(meta==null)return false;for(String raw:getConfig().getStringList("blacklist-custom-keys")){NamespacedKey key=NamespacedKey.fromString(raw);if(key!=null&&meta.getPersistentDataContainer().has(key))return true;}return false;}
  private void sync(Trade t, Player p, Inventory inv){ ItemStack[] target=t.offer(p.getUniqueId()); for(int i=0;i<27;i++){ItemStack item=inv.getItem(i); if(item != null && isBlacklisted(item)) { tell(p,msg("item-blacklisted")); item=null; inv.setItem(i,null); } target[i]=item==null?null:item.clone();} persistCustody(t); t.unlock();}
  private void refresh(Trade t){for(UUID id:List.of(t.a,t.b)){Player p=getServer().getPlayer(id);if(p!=null){redrawing.add(id);open(t,p);}}}
  @EventHandler public void activeClick(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player p)||!(e.getInventory().getHolder() instanceof ActiveHolder holder))return;e.setCancelled(true);int slot=e.getRawSlot();if(slot<0||slot>=holder.trades.size())return;Trade t=holder.trades.get(slot);Player a=getServer().getPlayer(t.a),b=getServer().getPlayer(t.b);tell(p,"&eActive trade: &f"+(a==null?t.a:a.getName())+" &7↔ &f"+(b==null?t.b:b.getName()));tell(p,"&7State: &f"+t.state+" &8• &7Money: &a"+t.moneyA+" &7/ &a"+t.moneyB);tell(p,"&7First offer: &f"+describeOffer(t.offerA));tell(p,"&7Second offer: &f"+describeOffer(t.offerB));}
  @EventHandler public void logClick(InventoryClickEvent e){
    if(!(e.getWhoClicked() instanceof Player p) || !(e.getInventory().getHolder() instanceof LogHolder holder)) return;
    e.setCancelled(true); int slot=e.getRawSlot(); if(slot==45&&holder.page>0){showLogs(p,holder.subject,holder.page-1);return;} if(slot==53&&(holder.page+1)*45<holder.entries.size()){showLogs(p,holder.subject,holder.page+1);return;} if(slot<0||slot>=45)return;int index=holder.page*45+slot;if(index>=holder.entries.size())return;LogEntry entry=holder.entries.get(index);tell(p,"&eTrade #"+entry.id+" &f"+entry.firstName+" &7↔ &f"+entry.secondName+" &7"+entry.status+" &8• &7"+entry.time+" &8• &7"+entry.reason+" &8• &a"+entry.firstMoney+" &7/ &a"+entry.secondMoney+" &8• &7"+entry.items);}
  @EventHandler public void recoveryClick(InventoryClickEvent e){
    if(!(e.getWhoClicked() instanceof Player p) || !(e.getInventory().getHolder() instanceof RecoveryHolder holder)) return;
    e.setCancelled(true); int slot=e.getRawSlot(); if(slot==45&&holder.page>0){showInbox(p,holder.page-1);return;} if(slot==53&&(holder.page+1)*45<holder.items.size()){showInbox(p,holder.page+1);return;} if(slot<0||slot>=45)return; int index=holder.page*45+slot; if(index>=holder.items.size())return;
    ItemStack item=holder.items.get(index); if(item==null)return;
    Map<Integer,ItemStack> overflow=p.getInventory().addItem(item.clone());
    if(!overflow.isEmpty()){tell(p,msg("recovery-full"));return;}
    holder.items.set(index,null); e.getInventory().setItem(slot,null); saveRecoveryList(p.getUniqueId(),holder.items); tell(p,msg("recovery-claimed"));
  }
  @EventHandler public void click(InventoryClickEvent e){
    if(!(e.getWhoClicked() instanceof Player p)||!(e.getInventory().getHolder() instanceof TradeHolder h))return;
    Trade t=h.trade; e.setCancelled(true);
    if(!trades.containsKey(p.getUniqueId()) || !h.viewer.equals(p.getUniqueId())) return;
    int raw=e.getRawSlot();
    // Only the owner may use their 27 offer slots. Shift, number-key,
    // double-click and offhand actions are rejected everywhere; plain
    // pickup/place clicks inside the player's own inventory stay allowed so
    // items can actually reach the cursor and be offered.
    if(raw>=54){
      InventoryAction act=e.getAction();
      if(act==InventoryAction.PICKUP_ALL||act==InventoryAction.PICKUP_HALF||act==InventoryAction.PICKUP_SOME||act==InventoryAction.PICKUP_ONE
        ||act==InventoryAction.PLACE_ALL||act==InventoryAction.PLACE_SOME||act==InventoryAction.PLACE_ONE||act==InventoryAction.SWAP_WITH_CURSOR)
        e.setCancelled(false);
      return;
    }
    if(raw>=0&&raw<27){
      if(t.locked(p.getUniqueId())) return;
      ItemStack current=e.getInventory().getItem(raw), cursor=e.getCursor();
      boolean right=e.isRightClick();
      if(cursor==null||cursor.getType()==Material.AIR){
        if(current!=null&&current.getType()!=Material.AIR){
          if(right&&current.getAmount()>1){ ItemStack one=current.clone();one.setAmount(1); e.setCursor(one); current.setAmount(current.getAmount()-1); e.getInventory().setItem(raw,current); }
          else { e.setCursor(current.clone()); e.getInventory().setItem(raw,null); }
        }
      } else if(current==null||current.getType()==Material.AIR){
        ItemStack put=cursor.clone(); if(right&&put.getAmount()>1)put.setAmount(1);
        e.getInventory().setItem(raw,put); cursor.setAmount(cursor.getAmount()-put.getAmount()); e.setCursor(cursor.getAmount()<=0?null:cursor);
      } else if(current.isSimilar(cursor) && current.getAmount()<current.getMaxStackSize()){
        int add=right?1:Math.min(cursor.getAmount(),current.getMaxStackSize()-current.getAmount()); current.setAmount(current.getAmount()+add); cursor.setAmount(cursor.getAmount()-add); e.getInventory().setItem(raw,current); e.setCursor(cursor.getAmount()<=0?null:cursor);
      } else { e.getInventory().setItem(raw,cursor.clone()); e.setCursor(current.clone()); }
      sync(t,p,e.getInventory()); refresh(t); return;
    }
    if(raw==45){if(economy==null){tell(p,msg("economy-unavailable"));return;}openMoneySign(p);return;}
    if(raw==47){if(t.locked(p.getUniqueId())){if(!fire(p,getServer().getPlayer(t.other(p.getUniqueId())),FairDealTradeEvent.Stage.UNLOCK,"Unlocked"))return;t.unlock();}else{if(!fire(p,getServer().getPlayer(t.other(p.getUniqueId())),FairDealTradeEvent.Stage.LOCK,"Locked"))return;t.lock(p.getUniqueId());sound(p,"locked");}refresh(t);return;}
    if(raw==49){cancel(t,"Cancelled by player");return;}
    if(raw==51&&t.bothLocked()){if(!fire(p,getServer().getPlayer(t.other(p.getUniqueId())),FairDealTradeEvent.Stage.CONFIRM,"Confirmed"))return;t.confirm(p.getUniqueId());if(t.bothConfirmed()) beginCountdown(t);else refresh(t);}
  }
  @EventHandler public void drag(InventoryDragEvent e){if(e.getInventory().getHolder() instanceof TradeHolder h)e.setCancelled(true);}
  @EventHandler public void close(InventoryCloseEvent e){if(e.getInventory().getHolder() instanceof TradeHolder h && trades.containsKey(e.getPlayer().getUniqueId()) && !moneyInput.contains(e.getPlayer().getUniqueId())) { if(redrawing.remove(e.getPlayer().getUniqueId())) return; if(e.getPlayer() instanceof Player p) sync(h.trade,p,e.getInventory()); cancel(h.trade,"Trade screen closed"); }}
  @EventHandler public void join(PlayerJoinEvent e){int pending=recoveryCount(e.getPlayer().getUniqueId());if(pending>0)tell(e.getPlayer(),msg("recovery-pending").replace("{count}",String.valueOf(pending)));}
  @EventHandler public void quit(PlayerQuitEvent e){signInputs.remove(e.getPlayer().getUniqueId());moneyInput.remove(e.getPlayer().getUniqueId());Trade t=trades.get(e.getPlayer().getUniqueId());if(t!=null)cancel(t,"Player disconnected");}
  @EventHandler public void death(PlayerDeathEvent e){signInputs.remove(e.getEntity().getUniqueId());moneyInput.remove(e.getEntity().getUniqueId());Trade t=trades.get(e.getEntity().getUniqueId());if(t!=null)cancel(t,"Player died");}
  private void openMoneySign(Player p){Location loc=p.getLocation().getBlock().getLocation();signInputs.put(p.getUniqueId(),loc);p.closeInventory();p.openVirtualSign(Position.block(loc.getBlockX(),loc.getBlockY(),loc.getBlockZ()),Side.FRONT);}
  @EventHandler public void signChange(SignChangeEvent e){Location expected=signInputs.remove(e.getPlayer().getUniqueId());if(expected==null||!expected.equals(e.getBlock().getLocation()))return;e.setCancelled(true);String input=e.getLine(0);e.getPlayer().getScheduler().run(this, task -> applyMoneyInput(e.getPlayer(),input), null);}
  private void applyMoneyInput(Player p,String input){if(economy==null){tell(p,msg("economy-unavailable"));return;}Trade t=trades.get(p.getUniqueId());if(t==null)return;if(input==null||input.equalsIgnoreCase("cancel")){open(t,p);return;}double amount=parse(input,economy.getBalance(p));double minimum=getConfig().getDouble("money.minimum",0.01);double maximum=getConfig().getDouble("money.maximum",1_000_000_000_000d);if(amount<minimum||amount>maximum||!economy.has(p,amount)){tell(p,msg("not-enough-money"));openMoneySign(p);return;}double old=t.money(p.getUniqueId());if(old>0){economy.depositPlayer(p,old);clearEscrow(p.getUniqueId());}t.setMoney(p.getUniqueId(),0);EconomyResponse r=economy.withdrawPlayer(p,amount);if(!r.transactionSuccess()){tell(p,msg("not-enough-money"));openMoneySign(p);return;}t.setMoney(p.getUniqueId(),amount);updateTransaction(t,"ESCROWED","Money reserved");persistCustody(t);saveEscrow(p.getUniqueId(),amount);t.unlock();open(t,p);Player other=getServer().getPlayer(t.other(p.getUniqueId()));if(other!=null)open(t,other);}
  /** Compatibility fallback for existing chat-input sessions created before a reload. */
  @EventHandler public void chat(AsyncPlayerChatEvent e){Player p=e.getPlayer();if(!moneyInput.remove(p.getUniqueId()))return;e.setCancelled(true);String input=e.getMessage();p.getScheduler().run(this, task -> applyMoneyInput(p,input), null);}
  private double parse(String raw,double balance){return MoneyAmountParser.parse(raw,balance,getConfig().getBoolean("money.accept-all-keyword",true));}
    private void saveEscrow(UUID owner,double amount){if(database==null)return;try(PreparedStatement s=database.prepareStatement("INSERT INTO escrow(owner_uuid,amount,updated_at) VALUES(?,?,?) ON CONFLICT(owner_uuid) DO UPDATE SET amount=excluded.amount,updated_at=excluded.updated_at")){s.setString(1,owner.toString());s.setDouble(2,amount);s.setString(3,Instant.now().toString());s.executeUpdate();}catch(SQLException e){getLogger().warning("Could not journal escrow: "+e.getMessage());}}
  private void clearEscrow(UUID owner){if(database==null)return;try(PreparedStatement s=database.prepareStatement("DELETE FROM escrow WHERE owner_uuid=?")){s.setString(1,owner.toString());s.executeUpdate();}catch(SQLException e){getLogger().warning("Could not clear escrow journal: "+e.getMessage());}}
  private File custodyFile(Trade t){return new File(getDataFolder(),"active-"+t.a+"-"+t.b+".yml");}
  private void persistCustody(Trade t){try{org.bukkit.configuration.file.YamlConfiguration y=new org.bukkit.configuration.file.YamlConfiguration();y.set("first",t.a.toString());y.set("second",t.b.toString());y.set("first-items",Arrays.asList(t.offerA));y.set("second-items",Arrays.asList(t.offerB));y.set("first-money",t.moneyA);y.set("second-money",t.moneyB);y.save(custodyFile(t));}catch(Exception e){getLogger().severe("Could not persist active trade custody: "+e.getMessage());}}
  @SuppressWarnings("unchecked") private void recoverCrashFiles(){File[] files=getDataFolder().listFiles((d,n)->n.startsWith("active-")&&n.endsWith(".yml"));if(files==null)return;for(File f:files)try{org.bukkit.configuration.file.YamlConfiguration y=org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(f);UUID first=UUID.fromString(y.getString("first"));UUID second=UUID.fromString(y.getString("second"));for(ItemStack i:(List<ItemStack>)(List<?>)y.getList("first-items",List.of()))if(i!=null)saveRecovery(first,i);for(ItemStack i:(List<ItemStack>)(List<?>)y.getList("second-items",List.of()))if(i!=null)saveRecovery(second,i);f.delete();}catch(Exception e){getLogger().severe("Could not recover "+f.getName()+": "+e.getMessage());}}
  private void clearCustody(Trade t){File f=custodyFile(t);if(f.exists()&&!f.delete())getLogger().warning("Could not remove completed custody record "+f.getName());}
  private void beginCountdown(Trade t){if(t.state!=TradeState.LOCKED)return;t.countingDown=true;t.state=TradeState.COUNTDOWN;int seconds=getConfig().getInt("confirmation-countdown-seconds",3);for(UUID id:List.of(t.a,t.b)){Player p=getServer().getPlayer(id);if(p!=null)p.sendTitle(ChatColor.GREEN+"Trade secured",ChatColor.YELLOW+"Completing in "+seconds+"...",5,40,5);}Player owner=getServer().getPlayer(t.a);if(owner==null){cancel(t,"Countdown owner unavailable");return;}owner.getScheduler().runDelayed(this,task->{if(trades.containsKey(t.a)&&t.state==TradeState.COUNTDOWN&&t.bothConfirmed())complete(t);},null,seconds*20L);}
  private synchronized void complete(Trade t){if(t.state!=TradeState.COUNTDOWN && t.state!=TradeState.LOCKED)return;t.state=TradeState.COMPLETING;updateTransaction(t,"COMPLETING","Both players confirmed");Player a=getServer().getPlayer(t.a),b=getServer().getPlayer(t.b);if(a==null||b==null){cancel(t,"Player unavailable");return;} if(!fire(a,b,FairDealTradeEvent.Stage.COMPLETE,"Completed")){cancel(t,"Completion blocked by another plugin");return;} // custody items are already removed from their owners
    deliver(a,t.offer(t.b));deliver(b,t.offer(t.a));if(economy!=null){if(t.moneyA>0){economy.depositPlayer(b,t.moneyA);clearEscrow(t.a);}if(t.moneyB>0){economy.depositPlayer(a,t.moneyB);clearEscrow(t.b);}}finish(t,"COMPLETED","Completed safely",true);}
  private synchronized void cancel(Trade t,String reason){if(t.state==TradeState.COMPLETED||t.state==TradeState.CANCELLED)return;t.state=TradeState.CANCELLED;Player a=getServer().getPlayer(t.a),b=getServer().getPlayer(t.b);if(a!=null){deliver(a,t.offer(t.a));if(economy!=null&&t.moneyA>0){economy.depositPlayer(a,t.moneyA);clearEscrow(t.a);}}if(b!=null){deliver(b,t.offer(t.b));if(economy!=null&&t.moneyB>0){economy.depositPlayer(b,t.moneyB);clearEscrow(t.b);}}finish(t,"CANCELLED",reason,false);}
  private void finish(Trade t,String status,String reason,boolean ok){t.state=ok?TradeState.COMPLETED:TradeState.CANCELLED;updateTransaction(t,ok?"COMPLETED":"REFUNDED",reason);clearCustody(t);trades.remove(t.a);trades.remove(t.b);log(t,status,reason);for(UUID id:List.of(t.a,t.b)){Player p=getServer().getPlayer(id);if(p!=null){p.closeInventory();tell(p,ok?msg("trade-completed"):msg("trade-cancelled"));sound(p,ok?"completed":"cancelled");}}}
  private void deliver(Player p,ItemStack[] items){for(ItemStack i:items)if(i!=null&&i.getType()!=Material.AIR){Map<Integer,ItemStack> left=p.getInventory().addItem(i);for(ItemStack x:left.values())saveRecovery(p.getUniqueId(),x);}}
  private void saveRecovery(UUID owner,ItemStack item){try{File f=new File(getDataFolder(),"recovery-"+owner+".yml");org.bukkit.configuration.file.YamlConfiguration y=org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(f);List<ItemStack> l=(List<ItemStack>)y.getList("items",new ArrayList<>());l.add(item);y.set("items",l);y.save(f);}catch(Exception e){getLogger().severe("Recovery save failed: "+e.getMessage());}}
  @SuppressWarnings("unchecked") private List<ItemStack> loadRecovery(UUID owner){File f=new File(getDataFolder(),"recovery-"+owner+".yml");return new ArrayList<>((List<ItemStack>)(List<?>)org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(f).getList("items",List.of()));}
  private void saveRecoveryList(UUID owner,List<ItemStack> items){try{File f=new File(getDataFolder(),"recovery-"+owner+".yml");org.bukkit.configuration.file.YamlConfiguration y=new org.bukkit.configuration.file.YamlConfiguration();y.set("items",items.stream().filter(Objects::nonNull).toList());y.save(f);}catch(Exception e){getLogger().severe("Recovery save failed: "+e.getMessage());}}
  private void showRecoveryView(Player staff,UUID owner){List<ItemStack> items=loadRecovery(owner);Inventory in=Bukkit.createInventory(new RecoveryViewHolder(),54,ChatColor.DARK_GRAY+"FairDeal Recovery View");for(int i=0;i<Math.min(54,items.size());i++)in.setItem(i,items.get(i));staff.openInventory(in);}
  private void showInbox(Player p){showInbox(p,0);}
  private void showInbox(Player p,int page){List<ItemStack> items=loadRecovery(p.getUniqueId());RecoveryHolder holder=new RecoveryHolder(items,page);Inventory in=Bukkit.createInventory(holder,54,ChatColor.translateAlternateColorCodes('&',getConfig().getString("recovery-title","&8FairDeal Recovery"))+" ("+(page+1)+")");for(int i=0;i<45;i++){int index=page*45+i;if(index<items.size())in.setItem(i,items.get(index));}if(page>0)in.setItem(45,button(Material.ARROW,"&ePrevious page","&7Click to browse"));if((page+1)*45<items.size())in.setItem(53,button(Material.ARROW,"&eNext page","&7Click to browse"));p.openInventory(in);}
  private void showActive(Player p){List<Trade> active=new ArrayList<>(new HashSet<>(trades.values()));ActiveHolder holder=new ActiveHolder(active);Inventory in=Bukkit.createInventory(holder,54,ChatColor.DARK_GRAY+"FairDeal Active Trades");for(int i=0;i<Math.min(54,active.size());i++){Trade t=active.get(i);Player a=getServer().getPlayer(t.a),b=getServer().getPlayer(t.b);in.setItem(i,button(Material.SPYGLASS,"&f"+(a==null?t.a:a.getName())+" &7↔ &f"+(b==null?t.b:b.getName()),"&7"+t.state+" • click to inspect"));}p.openInventory(in);}
  private void showLogDetail(Player p,LogEntry entry){Inventory in=Bukkit.createInventory(new LogDetailHolder(),27,ChatColor.DARK_GRAY+"FairDeal Trade #"+entry.id);in.setItem(11,button(entry.status.equals("COMPLETED")?Material.EMERALD:Material.BARRIER,"&f"+entry.status,"&7"+entry.reason));in.setItem(13,button(Material.GOLD_INGOT,"&6Money offers","&a"+entry.firstMoney+" &7/ &a"+entry.secondMoney));in.setItem(15,button(Material.CHEST,"&eItem summary","&7"+entry.items));in.setItem(22,button(Material.CLOCK,"&fTimestamp","&7"+entry.time));p.openInventory(in);}
  private void showLogs(Player p,UUID subject){showLogs(p,subject,0);}
  private void showLogs(Player p,UUID subject,int page){List<LogEntry> entries=new ArrayList<>();if(database!=null)try(PreparedStatement s=database.prepareStatement(subject==null?"SELECT * FROM trade_log ORDER BY id DESC":"SELECT * FROM trade_log WHERE first_uuid=? OR second_uuid=? ORDER BY id DESC")){if(subject!=null){s.setString(1,subject.toString());s.setString(2,subject.toString());}ResultSet r=s.executeQuery();while(r.next())entries.add(new LogEntry(r.getLong("id"),r.getString("time"),r.getString("status"),r.getString("reason"),r.getDouble("first_money"),r.getDouble("second_money"),r.getString("item_summary"),r.getString("first_name"),r.getString("second_name")));}catch(SQLException e){tell(p,"&cCould not read logs.");return;}LogHolder holder=new LogHolder(entries,subject,page);Inventory in=Bukkit.createInventory(holder,54,ChatColor.translateAlternateColorCodes('&',getConfig().getString("log-title","&8FairDeal History"))+" ("+(page+1)+")");for(int i=0;i<45;i++){int index=page*45+i;if(index<entries.size()){LogEntry r=entries.get(index);in.setItem(i,button(r.status.equals("COMPLETED")?Material.EMERALD:Material.BARRIER,"&f"+(r.firstName==null?"Unknown":r.firstName)+" &7↔ &f"+(r.secondName==null?"Unknown":r.secondName),"&7#"+r.id+" • "+r.status+" • click for details"));}}if(page>0)in.setItem(45,button(Material.ARROW,"&ePrevious page","&7Click to browse"));if((page+1)*45<entries.size())in.setItem(53,button(Material.ARROW,"&eNext page","&7Click to browse"));p.openInventory(in);}
  private String format(double v){return economy==null?"Unavailable":economy.format(v);}
  @Override public List<String> onTabComplete(CommandSender s,Command c,String a,String[] args){String prefix=args.length==0?"":args[args.length-1].toLowerCase(Locale.ROOT);List<String> values=new ArrayList<>();if(c.getName().equalsIgnoreCase("fairdealadmin")){if(args.length==1)values.addAll(List.of("reload","logs","inbox","active","diagnostics"));else if(args.length==2&&(args[0].equalsIgnoreCase("logs")||args[0].equalsIgnoreCase("inbox")))for(Player player:getServer().getOnlinePlayers())values.add(player.getName());}else if(args.length==1){values.addAll(List.of("accept","deny","cancel","inbox","log","toggle"));for(Player player:getServer().getOnlinePlayers())values.add(player.getName());}return values.stream().filter(value->value.toLowerCase(Locale.ROOT).startsWith(prefix)).sorted().toList();}
  private record Request(UUID from,long expires){}
  private static final class LogDetailHolder implements InventoryHolder {public Inventory getInventory(){return null;}}
  private static final class ActiveHolder implements InventoryHolder {final List<Trade> trades;ActiveHolder(List<Trade> trades){this.trades=trades;}public Inventory getInventory(){return null;}}
  private record LogEntry(long id,String time,String status,String reason,double firstMoney,double secondMoney,String items,String firstName,String secondName){}
  private static final class LogHolder implements InventoryHolder {final List<LogEntry> entries;final UUID subject;final int page;LogHolder(List<LogEntry> entries,UUID subject,int page){this.entries=entries;this.subject=subject;this.page=page;}public Inventory getInventory(){return null;}}
  private static final class RecoveryViewHolder implements InventoryHolder {public Inventory getInventory(){return null;}}
  private static final class RecoveryHolder implements InventoryHolder {final List<ItemStack> items;final int page;RecoveryHolder(List<ItemStack> items,int page){this.items=items;this.page=page;}public Inventory getInventory(){return null;}}
  private static final class TradeHolder implements InventoryHolder {final Trade trade;final UUID viewer;TradeHolder(Trade t,UUID v){trade=t;viewer=v;}public Inventory getInventory(){return null;}}
  private enum TradeState { OPEN, LOCKED, COUNTDOWN, COMPLETING, COMPLETED, CANCELLED }
  private static final class Trade {final UUID id=UUID.randomUUID();final UUID a,b; TradeState state=TradeState.OPEN;final ItemStack[] offerA=new ItemStack[27],offerB=new ItemStack[27];double moneyA,moneyB;boolean lockA,lockB,confirmA,confirmB,countingDown;Trade(UUID a,UUID b){this.a=a;this.b=b;}UUID other(UUID x){return x.equals(a)?b:a;}ItemStack[] offer(UUID x){return x.equals(a)?offerA:offerB;}double money(UUID x){return x.equals(a)?moneyA:moneyB;}void setMoney(UUID x,double v){if(x.equals(a))moneyA=v;else moneyB=v;}boolean locked(UUID x){return x.equals(a)?lockA:lockB;}boolean confirmed(UUID x){return x.equals(a)?confirmA:confirmB;}void lock(UUID x){if(x.equals(a))lockA=true;else lockB=true;if(lockA&&lockB)state=TradeState.LOCKED;}void unlock(){lockA=lockB=confirmA=confirmB=countingDown=false;state=TradeState.OPEN;}boolean bothLocked(){return lockA&&lockB;}void confirm(UUID x){if(x.equals(a))confirmA=true;else confirmB=true;}boolean bothConfirmed(){return confirmA&&confirmB;}}
}
