package dev.superseller.shardtools.config;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.minimessage.MiniMessage;
import org.bukkit.command.CommandSender;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.java.JavaPlugin;

/**
 * MiniMessage-based translation layer backed by messages.yml.
 *
 * Self-healing: any key that is missing from the server's messages.yml (for
 * example because the file was generated by an older plugin version) is
 * automatically merged in from the packaged defaults, so raw message keys
 * like "shop.balance-item" are never shown to players.
 */
public final class Messages {

    private final JavaPlugin plugin;
    private final MiniMessage mini = MiniMessage.miniMessage();
    private YamlConfiguration messages = new YamlConfiguration();
    private String prefix = "";

    public Messages(JavaPlugin plugin) {
        this.plugin = plugin;
        reload();
    }

    public void reload() {
        File file = new File(plugin.getDataFolder(), "messages.yml");
        if (!file.isFile()) {
            plugin.saveResource("messages.yml", false);
        }
        messages = YamlConfiguration.loadConfiguration(file);
        messages.setDefaults(packagedDefaults());

        // Merge keys that the server's file is missing (e.g. added by an
        // update) so admins can see and edit them. A second defaults-free
        // copy of the file detects what is really absent.
        YamlConfiguration defaults = packagedDefaults();
        YamlConfiguration userOnly = YamlConfiguration.loadConfiguration(file);
        boolean changed = false;
        for (String key : defaults.getKeys(true)) {
            String value = defaults.getString(key);
            if (value != null && userOnly.getString(key) == null) {
                messages.set(key, value);
                changed = true;
            }
        }
        if (changed) {
            try {
                messages.save(file);
                plugin.getLogger().info("Added missing message keys to messages.yml");
            } catch (IOException error) {
                plugin.getLogger().log(Level.WARNING, "Could not update messages.yml", error);
            }
        }
        prefix = messages.getString("prefix", "");
    }

    private YamlConfiguration packagedDefaults() {
        YamlConfiguration embedded = new YamlConfiguration();
        try {
            InputStream resource = plugin.getResource("messages.yml");
            if (resource != null) {
                embedded = YamlConfiguration.loadConfiguration(
                        new InputStreamReader(resource, StandardCharsets.UTF_8));
            }
        } catch (Throwable error) {
            plugin.getLogger().log(Level.WARNING, "Could not read packaged messages.yml", error);
        }
        return embedded;
    }

    /** Renders a message key to a component, applying %token% replacements. */
    public Component get(String key, String... replacements) {
        return mini.deserialize(apply(prefix + raw(key, replacements)));
    }

    /** Renders without the prefix (for lore lines and titles). */
    public Component bare(String key, String... replacements) {
        return mini.deserialize(raw(key, replacements));
    }

    /**
     * Renders raw MiniMessage text for item names/lore. Minecraft renders
     * custom item names and lore in italics by default; the leading
     * {@code <!italic>} tag disables that so shop items show upright text.
     */
    public Component itemText(String text) {
        return mini.deserialize("<!italic>" + text);
    }

    /** Renders a message key as a non-italic item name/lore line. */
    public Component itemLine(String key, String... replacements) {
        return mini.deserialize("<!italic>" + raw(key, replacements));
    }

    public String raw(String key, String... replacements) {
        String text = messages.getString(key);
        if (text == null) {
            text = humanize(key);
        }
        return apply(text, replacements);
    }

    public void send(CommandSender target, String key, String... replacements) {
        target.sendMessage(get(key, replacements));
    }

    public MiniMessage miniMessage() {
        return mini;
    }

    /** Last-resort fallback so a missing key never shows as "a.b-c". */
    private static String humanize(String key) {
        String last = key.substring(key.lastIndexOf('.') + 1);
        return last.replace('-', ' ');
    }

    private static String apply(String text, String... replacements) {
        for (int i = 0; i + 1 < replacements.length; i += 2) {
            text = text.replace(replacements[i], replacements[i + 1]);
        }
        return text;
    }
}
